### ISSUE TITLE
Which version should I use for a new project?

### ISSUE THREAD

**Issue by sim1camporeale** [vimeo/turnstile-android#33]
According to the README.md I should use version 0.8.0. 
If I look into the master branch the latest stable release is 1.0.1. 
Additional features stated inside the readme (i.e. concurrent task handling) seems to be implemented only in version 1.0.2. There is a pending pull request that aims to merge 1.0.2 version inside the **master** branch. 

Which version of this library should I use in a production app? 
Can I use latest commits in **develop** branch or I need to wait for your pull request to be approved and merged?

Thank for your support.

**Comment by kvenn** [comment]
Hi Simone,

We've recently decided to make some larger changes to the library to make it less prone to breaking as we make changes (while still maintaining a similar level of customizability). Because of that, this library is currently a "Work In Progress". While we make these changes, I'd suggest using another task queue library that will hopefully give you a similar feature set as `turnstile` until `turnstile` is more stable.

Below is a list of some other task queue options. If you'd still like to use turnstile after reviewing the list, I'd recommend using the `develop` branch as a submodule - but as a warning we are likely going to make changes to the API of `turnstile`. 

<h2>Other task queue options</h2>
<p>
    If you don't think you'll benefit from the customizability of this library, there are many other options that are each excellent in their own way (this list is not exhaustive).
</p>
<ul>
    <li>
        android-priority-jobqueue
        <ul>
            <li>
                Pros: Most of the <a href="#features">features above</a>. Additionally has prioritization of jobs, job delay, load balancing, and grouping
            </li>
            <li>
                Cons: Doesn't run in a Service (dies with your application). It's difficult to extend or customize.
            </li>
        </ul>
    </li>
    <li>
        tape
        <ul>
            <li>
                Pros: Most of the <a href="#features">features above</a>. Very easy to implement for simple tasks.
            </li>
            <li>
                Cons: No progress broadcasting or awareness of network. It's difficult to extend or customize.
            </li>
        </ul>
    </li>
    <li>
        robospice
        <ul>
            <li>
                Pros: Good for long running network requests.
            </li>
            <li>
                Cons: It's difficult to extend or customize. It also has a limited feature set.
            </li>
        </ul>
    </li>
</ul>

**Comment by sim1camporeale** [comment]
Thanks @kvenn for your help.
I'm evaluating to use your`develop` branch or switch to `android-priority-jobqueue`.
I really like the way you are working on `turnstile` library and your effort in achieving a great level of customizability.
I need to extend your library to support `pause` and `resume` at task level.
I'll follow this project to be updated on next progress.

Great job!

**Comment by kvenn** [comment]
Marking as closed 📕
